### ISSUE TITLE
Ctrl-V / paste didn't work

### ISSUE THREAD

**Issue by mchen6** [whoGloo/nodespeed-ide#8]
Dear nodespeed-ide maintainers, thanks for the great contributions.

I clone and build nodespeed-ide successfully in my local environment, but it seems for now the Ctrl-V / paste feature won't work in the editor, while Ctrl-X / cut and Ctrl-C / copy works fine. Is this a missing feature?

**Comment by asthomasdk** [comment]
We have not developed the terminal parts ourselves. We are using a version of [xterm.js](https://xtermjs.org/), which we have adapted a little bit to fit into the IDE and to run in a stand-alone browse tab together with the IDE. 

We have not managed to get using the CTRL- keys for copy and paste to work - but have been using Ctrl-Insert and Shift-Insert for this instead - which works nicely. 

I have not loked at the xterm.js project in a while, but expect this has been updated since we implemented it. So it may be worthwhile to have a look at this and see if you can get what you need. 

If you come up with something useful -with this or pother parts of the project, feel free to make a PR ;-) 

HTH

/Thomas

**Comment by mchen6** [comment]
Here is a few findings. I did a code compare to the brackets-src submodule to the same submodule in original rabchev/brackets-server branch, which supports Ctrl-V pasting. In brackets-src/editor/EditorCommandHandler.js if I use the original ignoreCommand() code to handle Ctrl-V (instead using window.document.executeCommand('paste') in the new code) it would work fine. But I still don't understand the cause of this problem.

**Comment by asthomasdk** [comment]
I misunderstood your initial comment and thought it was for the terminal we have included. 

In the IDE itself we have also been limited to using Ctrl-Insert and Shift-Insert. I have not looked into why this was a problem - but assumed it was related to running things in a browser.

**Comment by mchen6** [comment]
It was my bad that I didn't clearly specify my test environment: I took below steps to run nodespeed-ide on Ubuntu: 
1. clone nodespeed-ide repo
2. git submodule update --recursive --init
3. npm install
4. grunt build
5. node ./nodespeedide.js

And then I opened http://localhost:6800/ and entered nodespeed-ide editor in browser. Then I found Ctrl-V won't work until I make above change to brackets-src/src/editor/EditorCommandHandler.js

However since I didn't understand why this fix works so I consider this is only a workaround for now.
